#! /bin/sh

ninja() {
	cd ~
	rm -rf $dir
	exit
}

echo loading...

info="$(gifsicle -I $1)"
dir="/tmp/gif/$$"

mkdir /tmp/gif 2>/dev/null
mkdir $dir
cp $1 $dir/
cd $dir

trap ninja SIGHUP SIGINT SIGTERM

xx=$(echo "$info" | grep screen | awk '{print $3}' | awk -F x '{print $1}')
yy=$(echo "$info" | grep screen | awk '{print $3}' | awk -F x '{print $2}')
#delay=$(echo "$info" | grep delay | head -1 | awk '{print $NF}' | tr -d 's')
delay=$(echo "$info" | grep delay | awk '{print $NF}' | tr -d 's')
img=$(echo "$info" | grep 'image ')

:<<DEBUG
echo "$info"
echo $dir
echo $xx $yy $delay 
echo "$delay"
DEBUG

#:<<DEFAULTDELAY
if [ ! "$delay" ]; then
	delay="0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n0.1\n"
fi
#DEFAULTDELAY

gifsicle -e $1
touch oa

#:<<transparency
offset=""
trans=$(echo "$info" | grep transparent | grep 255)
if [[ $trans ]]; then
	i=0;
	j=$(ls -1 | grep gif.000)
	for f in *gif.*; do
		i=$((i+1))
		echo "$offset"
		if [ "$offset" ]; then
			composite -geometry "$offset" $f $j $f
		else 
			composite $f $j $f
		fi	
		offset="+$(echo "$img" | grep at | awk '{print $6}' | sed -n "${i}p" | tr ',' '+')"
		j=$f;
	done
fi
#transparency

clear

############################

termres() {
	wx=$(xwininfo -id $WINDOWID | grep Width | awk '{print $2}')
	wy=$(xwininfo -id $WINDOWID | grep Height | awk '{print $2}')
	if [[ $xx -gt $wx ]]; then
		y=$(echo "$yy*$wx/$xx" | bc) 
		if [[ $y -gt $wy ]]; then
			echo "$xx*$wy/$yy" | bc > xx
			echo $wy > yy
		else
			echo $wx > xx
			echo $y > yy
		fi
	elif [[ $yy -gt $wy ]]; then
		echo "$xx*$wy/$yy" | bc > xx
		echo $wy > yy
	else
		echo $xx > xx
		echo $yy > yy
	fi
	echo "$(cat xx)*$(cat yy)" | bc > na
		
}
nxtFrm() {
	echo -e "0;1;0;0;$(cat xx);$(cat yy);;;;;$f\n3;" 

	if [[ $(cat na) -ne $(cat oa) ]]; then
		echo $(cat na) > oa
	fi
}

termres
#:<<LOOP
output_gen() {
	while true; do
		i=0
		for f in *gif.*; do
			i=$((i+1))
			sleep "$(echo "$delay" | sed -n "${i}p")"
			nxtFrm &
			termres &
		done
	done
}
#LOOP

#output_gen | /home/derpy/Documents/git/w3m/w3mimgdisplay
#output_gen | /home/derpy/Documents/git/w3mimgdisplay/w3mimgdisplay
output_gen | /usr/libexec/w3m/w3mimgdisplay
#output_gen 
